//@ Dungeon theme: the Hollow Roots (Wildwood, under the Ancient Grove; boss Amanita, the Sporemother): its roster, palette and tile kit (Root Cathedral, Sap Cellar, Fungus Alcove, Crawlway, Root Bend, Heartwood Knot, Seed Nook, Burrow Mouth)
/* One defineDungeonTheme call (shared/dungeons.js says the fields); design: docs/DUNGEON-THEMES.md section 3. Legend (besides # wall . floor S mouth O objective C cache P portal B boss spot):
     R root wall (solid: the roots massed into the walls)    I root pillar (solid: the hall's four)    T root trunk (solid, 2 x 2)    m mushroom cluster (solid)
     k knotted heartwood (solid, round the Heartwood Knot)    f glowing fungus (floor, a green light)    s sap pool (floor, an amber light)    n seed pods (floor)
     ^ root spikes (floor; hazard 'spikes': the rooted floors, where the run sets off the Rootwarden's root telegraph)    G guardian post (floor: the Rotwood in the alcove, the Ancient Treant in the knot)
   Tiles are drawn with their rim closed; `shapes` lists the door shapes each comes in (dgCarve opens the doors). The hall's pillars and mouths are DG_HALL_PILLARS / DG_HALL_MOUTHS. */
defineDungeonTheme({
  id:'hollowroots', name:'The Hollow Roots', land:'home', at:'Ancient Grove', lv:30,
  mobs:{walkers:['treant','deathcap','shroom','bogslime','direboar'], guardians:['ancient','rotwood']},
  boss:'amanita', music:'wild3',
  pal:{wall:0x3a2a1c, floor:0x2a2218, fog:0x120d08, light:0xe0a040},
  legend:{
    R:{solid:true, prop:'rootwall'}, I:{solid:true, prop:'rootpillar'}, T:{solid:true, prop:'roottrunk'}, m:{solid:true, prop:'mushrooms'}, k:{solid:true, prop:'heartknot'},
    f:{solid:false, prop:'glowfungus', light:0xb8f070}, s:{solid:false, prop:'sappool', light:0xe0a040}, n:{solid:false, prop:'seedpods'},
    '^':{solid:false, prop:'rootspikes', hazard:'spikes'}, G:{solid:false, prop:'guardpost', post:'guardian'}},
  tiles:[
    {id:'cathedral', tags:['hall'], w:1, shapes:['dead','straight','bend','tee','cross'], art:[   // the Root Cathedral: the boss circle ringed by trunks of root
      '########################',
      '########RRRRRRRR########',
      '######RRR......RRR######',
      '####RRR..f....f..RRR####',
      '###RR......s.......RR###',
      '###R.S............S.R###',
      '##RR..II........II..RR##',
      '##R...II....f...II...R##',
      '#RR..................RR#',
      '#R.f..................R#',
      '#R....................R#',
      '#R.................s..R#',
      '#R..s..f....B...f.....R#',
      '#R....................R#',
      '#R..................f.R#',
      '#RR..................RR#',
      '##R...II...f....II...R##',
      '##RR..II........II..RR##',
      '###R.S............S.R###',
      '###RR.......s......RR###',
      '####RRR.f......f.RRR####',
      '######RRR......RRR######',
      '########RRRRRRRR########',
      '########################']},
    {id:'sapcellar', tags:['room'], w:3, shapes:['dead','straight','bend','tee','cross'], art:[   // the Sap Cellar: amber pools, two old trunks, a rooted corner
      '########################',
      '########################',
      '########################',
      '###RRRRRRRRRRRRRRRRRR###',
      '###R.f....s.......f.R###',
      '###R....s..s....S...R###',
      '###R..TT.........^^.R###',
      '###R..TT..ss.....^^.R###',
      '###R.....ssss.......R###',
      '###R.S....ss....f...R###',
      '###R................R###',
      '###R..f..........s..R###',
      '###R.........s..sss.R###',
      '###R....^^......ss..R###',
      '###R....^^..........R###',
      '###R.s..........TT..R###',
      '###R.ss...S.....TT..R###',
      '###R.f.........f....R###',
      '###R................R###',
      '###R....s...........R###',
      '###RRRRRRRRRRRRRRRRRR###',
      '########################',
      '########################',
      '########################']},
    {id:'fungusalcove', tags:['room'], w:3, shapes:['dead','straight','bend','tee','cross'], art:[   // the Fungus Alcove: a round cave of mushroom clusters, the Rotwood's post in the middle
      '########################',
      '########################',
      '########################',
      '########################',
      '########RRRRRRRR########',
      '######RRR......RRR######',
      '#####RR..f....f..RR#####',
      '#####R............R#####',
      '####RR..m......m..RR####',
      '####R.......f^^....R####',
      '####R............f.R####',
      '####R..S...........R####',
      '####R.......G...S..R####',
      '####R.f............R####',
      '####R.....^^.......R####',
      '####RR..m......m..RR####',
      '#####R............R#####',
      '#####RR...f...f..RR#####',
      '######RRR......RRR######',
      '########RRRRRRRR########',
      '########################',
      '########################',
      '########################',
      '########################']},
    {id:'crawlway', tags:['pass'], w:3, shapes:['dead','straight','bend','tee','cross'], art:[   // the Crawlway: low tunnels meeting in a knot of roots
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########RRRRRRRR########',
      '########R......R########',
      '########R.^..f.R########',
      '########R......R########',
      '########R......R########',
      '########R.f..^.R########',
      '########R......R########',
      '########RRRRRRRR########',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################']},
    {id:'rootbend', tags:['pass'], w:2, shapes:['dead','straight','bend','tee','cross'], art:[   // a root trunk the tunnels go round
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '#######RRRRRRRRRR#######',
      '#######Rf......sR#######',
      '#######R........R#######',
      '#######R........R#######',
      '#######R...TT...R#######',
      '#######R...TT...R#######',
      '#######R........R#######',
      '#######R........R#######',
      '#######R^^.....fR#######',
      '#######RRRRRRRRRR#######',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################']},
    {id:'heartknot', tags:['site'], w:1, shapes:['dead','straight','bend','tee','cross'], art:[   // the Heartwood Knot: the objective inside a knot of heartwood open on four sides, the Ancient Treant on guard
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '######RRRRRRRRRRRR######',
      '######Rf........fR######',
      '######R..........R######',
      '######R.s........R######',
      '######R...kk.kk..R######',
      '######R...k...k..R######',
      '######R.....O....R######',
      '######R...k...k..R######',
      '######R...kk.kks.R######',
      '######R.G........R######',
      '######R.........fR######',
      '######RRRRRRRRRRRR######',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################']},
    {id:'seednook', tags:['cache'], w:1, shapes:['dead'], art:[   // the Seed Nook: a dead end full of seed pods
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '#######RRRRRRRRRR#######',
      '#######Rfn....nfR#######',
      '#######R........R#######',
      '#######R....C...R#######',
      '#######Rn.......R#######',
      '#######R.......nR#######',
      '#######R........R#######',
      '#######R........R#######',
      '#######R........R#######',
      '#######RRRRRRRRRR#######',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################']},
    {id:'burrow', tags:['start'], w:1, shapes:['dead'], art:[   // the Burrow Mouth: where you come down from the Hollowed Elder
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '#######RRRRRRRRRR#######',
      '#######Rf......fR#######',
      '#######R..s.....R#######',
      '#######R........R#######',
      '#######R....P...R#######',
      '#######R........R#######',
      '#######R........R#######',
      '#######Rf......fR#######',
      '#######R........R#######',
      '#######RRRRRRRRRR#######',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################',
      '########################']}]});
