//@ The quest board panel (Maren) and the quest log: notices, quests in progress, hand-ins (all generated by the server)
let qT=0;
function updateQuests(dt){ qT-=dt; if(qT>0) return; qT=0.5; renderQlog(); if(!$('#quests').hidden) renderQuests(); }
const qDefs=()=>(GEAR.q&&GEAR.q.defs)||{};
function acceptQuest(id){ if(Object.keys(GEAR.q.active).length>=QUEST_MAX_ACTIVE){ toast('You can carry five quests at a time','bad'); UI_SFX.error(); return; } netSend({t:'accept',id}); UI_SFX.click(); }
function turnIn(id){ netSend({t:'turnin',id}); }
function abandonQuest(id){ netSend({t:'abandon',id}); UI_SFX.click(); }
function openQuests(n){ openPanel('quests',n); renderQuests(); }
const KIND_LABEL={hunt:'Hunt',bounty:'Bounty',scout:'Scout',boss:'Boss'};
function qCard(q,btn,extra){
  const r=q.reward||questRewardFor(q), it=rewardItemText(r.item);
  const lv=q.level>PL.level?'req bad':q.level<PL.level-2?'req low':'req';
  return `<div class="qc k-${q.kind}"><div class="qc-top"><span class="qk">${KIND_LABEL[q.kind]||''}</span><b>${q.title}</b><span class="${lv}">Level ${q.level}</span></div><p>${q.text}</p>
    <div class="qc-bot"><span>${extra||''}</span><span class="rw">${r.xp} XP &nbsp; ${r.coins} coins${it?` &nbsp; <b class="qi">+ ${it}</b>`:''}</span>${btn||''}</div></div>`;
}
function renderQuests(){
  const n=panelNPC; if(!n||$('#quests').hidden) return;
  $('#qTitle').textContent='The quest board';
  const Q=GEAR.q, D=qDefs(), ids=Object.keys(Q.active);
  let h='';
  const ready=ids.filter(id=>Q.ready.includes(id)), going=ids.filter(id=>!Q.ready.includes(id));
  if(ready.length){ h+='<div class="inv-h">Ready to hand in</div>'; for(const id of ready) h+=qCard(D[id],`<button class="chip buy" data-turnin="${id}">Hand in</button>`,'Done'); }
  if(going.length){ h+=`<div class="inv-h">In progress <span>${ids.length} / ${QUEST_MAX_ACTIVE}</span></div>`; for(const id of going) h+=qCard(D[id],`<button class="chip" data-abandon="${id}">Abandon</button>`,qProgress(D[id])); }
  const mins=Math.max(1,Math.round((1-dayClock)*DAY_SECONDS/60));
  h+=`<div class="inv-h">On the board <span>new notices at sunrise, in about ${mins} min, and when you level up</span></div>`;
  const full=ids.length>=QUEST_MAX_ACTIVE;
  for(const q of Q.offers||[]) h+=qCard(q,`<button class="chip" data-accept="${q.id}" ${full?'disabled':''}>Accept</button>`,q.type==='kill'?'Defeat '+q.count:'Go and look');
  if(full) h+='<p class="muted">You are carrying five quests. Finish or abandon one to take another.</p>';
  $('#qBody').innerHTML=h;
  $('#qBody').querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptQuest(b.dataset.accept));
  $('#qBody').querySelectorAll('[data-turnin]').forEach(b=>b.onclick=()=>turnIn(b.dataset.turnin));
  $('#qBody').querySelectorAll('[data-abandon]').forEach(b=>b.onclick=()=>{ if(b.dataset.sure){ abandonQuest(b.dataset.abandon); return; } b.dataset.sure='1'; b.textContent='Tap again to abandon'; });
}
// where to go: kill quests point at the monster's zone, scout quests at the place
function questTarget(q){
  if(q.type==='visit') return {x:q.at.x,z:q.at.z,name:q.place};
  const bd=BOSS_DEFS.find(b=>b.def.id===q.target);
  if(bd){ const A=ARENAS.find(a=>a.key===bd.arena); return {x:A.x,z:A.z,name:A.name}; }
  const zn=ZONES.find(z=>MON_DEFS.find(d=>d.id===q.target&&d.level===z.key)); if(!zn) return null;
  const [x,z]=zonePoint(zn,0,0.5); return {x,z,name:zn.name,zone:zn};
}
function qProgress(q){
  const T=questTarget(q), here=T&&(T.zone?zoneAt(P.x,P.z)===T.zone:Math.hypot(T.x-P.x,T.z-P.z)<(q.r||20));
  const where=T?(here?'you are here':T.name+', '+Math.round(Math.hypot(T.x-P.x,T.z-P.z))+' m '+dirWord(T.x-P.x,T.z-P.z)):'';
  if(q.type==='visit') return 'Walk to '+where;
  return 'Defeated '+(GEAR.q.active[q.id]||0)+' of '+q.count+(where?' &middot; '+where:'');
}
function renderQlog(){
  const el=$('#qlog'), Q=GEAR.q, ids=Object.keys(Q.active||{}), D=qDefs();
  if(!ids.length||!started){ el.hidden=true; return; }
  el.hidden=false;
  el.innerHTML=ids.map(id=>{ const q=D[id]; if(!q) return ''; const ready=Q.ready.includes(id);
    return `<div class="ql${ready?' ok':''}"><b>${q.title}</b><span>${ready?'Done! Return to the quest board':qProgress(q)}</span></div>`; }).join('');
}
