// Writes docs/MOBS.md (every monster and its stats) and docs/EQUIPMENT.md (every piece of gear and tool) from the live code in src/, each with the file:line
// it is defined at, so the lists cannot drift from the game. No build needed.
//   node tools/gen-docs.js          write both files
//   node tools/gen-docs.js --check  exit 1 if the DATA in either file is out of date (stats, names, counts); a file whose only difference is
//                                   that quoted line numbers moved is reported as "refs moved" and passes (editing any quoted file shifts lines);
//                                   add --strict to fail on that too. Writes nothing.
// Run it after changing monster-defs.js, items.js, balance.js, drops.js, zones, the boss kits or any file whose line number the docs quote.
const fs=require('fs'), path=require('path');
const {ROOT,loadServer}=require('./load');
const NAMES=['FAM','MON_DEFS','ALL_MON_DEFS','BOSS_DEFS','GREY_DEFS','MONS','ZONES','defZone','MATS','BOSS_SKILLS','SKILLS','CLASSES','BOSS_QUESTS','BOSS_DROPS',
  'DROP_CHANCE','BOSS_SKILL_CHANCE','MAX_ZONE_LV','ITEM_LIST','TOOL_LIST','TIER_LV','TIERS','RARITY','RAR_KEY','RAR_MULT','SLOT_NAMES','PRICE','SLOT_PRICE','TIER_ATK',
  'ARMOR_HP','ARMOR_DEF','setHP','setDef','TOOL_MAT','TOOL_PRICE','TOOL_EXTRA','TOOL_KIND','TOOL_PROF','TOOL_SLOTS','craftCost','ORE_GRADES','LOG_GRADES','sellPrice',
  'CLASS_OF','WEAPON_SLOTS','ARMOR_SLOTS','MERGE_COUNT','SHOP_STEP','CRAFT_MAX_RAR','tierFor','fLv','expDmg','expHP','expRed','xpFor','expToNext','highMult','defRed',
  // the dungeons (version2): bosses, themes and their mob pools, the level-30 gear, rings and tempering
  'DG_BOSS_DEFS','DG_THEMES','DG_LANDS','DG_LV','DG_ELITE_HP','DG_REWARDS','DG_REWARD_W','DG_NAMES','DG_GEAR_LV','RING_ELS','RING_NAMES','RING_PCT','ENH_MAX','ENH_STEP','ENH_LV','ENH_DROP','ENH_NAME',
  'dgItem','dgGearId','dgRingId','dgAllIds','ITEM','POT_BUFF','passiveValue','SKILL_MAX_LV','DMG_TAKEN_MIN','RED_CAP'];
const {x:W}=loadServer({send(){},broadcast(){}},NAMES);
const CHECK=process.argv.includes('--check'), STRICT=process.argv.includes('--strict');

// ---- finding where things are defined (1-based line numbers, so the docs quote file:line) ----
const cache={};
const srcLines=f=>cache[f]||(cache[f]=fs.readFileSync(path.join(ROOT,f),'utf8').split('\n'));
function lineOf(f,re){ const i=srcLines(f).findIndex(l=>re.test(l)); if(i<0) throw new Error('gen-docs: nothing in '+f+' matches '+re); return i+1; }
const loc=(f,re)=>f+':'+lineOf(f,re);
const SH='src/shared/', SV='src/server/', GC='src/game/combat/';
const rowsOf=(headers,rows)=>['| '+headers.join(' | ')+' |','|'+headers.map(()=>'---').join('|')+'|',...rows.map(r=>'| '+r.join(' | ')+' |')].join('\n');
const num=n=>Number.isInteger(n)?String(n):n.toFixed(1);
const code=s=>'`'+s+'`';
const upper=s=>s[0].toUpperCase()+s.slice(1);
const HEADER=(name,about)=>'# '+name+'\n\n<!-- generated by node tools/gen-docs.js: do not edit by hand, change the code and run it again -->\n'+about+'\n\n'+
  'Generated from the live code by `node tools/gen-docs.js` (`--check` tells you when this file is out of date). Line numbers are those of the code when it was generated.\n\n';

// =====================================================================  MOBS.md
const MON_DEF_FILE=SH+'monster-defs.js';
const coinsAvg=(d,L)=>Math.max(1,Math.round(W.fLv(L)*2*Math.pow(1.1,Math.max(0,L-5))*W.highMult(L)))*(d.boss?20:1);   // coinsFor(L) rolls 1.5..2.5, so 2 is its mean
const countOf=d=>W.MONS.filter(m=>m.def.id===d.id).length;
function defRef(d){ return loc(MON_DEF_FILE,d.grey?new RegExp("greyDef\\('\\w+','"+d.id+"'"):new RegExp("\\bid:'"+d.id+"'")); }
function zoneOf(d,arena){ const zn=arena?W.ZONES.find(z=>z.key===arena):W.defZone(d); return zn?zn.name:'—'; }
function landOfZone(zn){ return zn.hoar?'hoar':zn.vale?'vale':zn.ring===3?'edge':'ring'; }
const MON_HEAD=['Id','Name','Lv','El','HP','Hits','Dmg','Atk s','Spd','Aggro','XP','Coins','Count','Zone','Drop','Model','Defined'];
function monRow(d){
  const L=d.level, mat=W.MATS[d.id];
  return [code(d.id),d.name,L,d.el||'—',d.hp,num(d.hp/W.expDmg(L)),d.dmg,d.atk,d.speed,d.aggro?d.aggro+' m':'passive',num(d.xp),d.noXp?'—':coinsAvg(d,L),
    countOf(d)||'on demand',zoneOf(d),mat?mat.name:'—',d.model+' ×'+d.scale,defRef(d)];
}
const monTable=defs=>rowsOf(MON_HEAD,defs.map(monRow));
const groups={ring:[],edge:[],vale:[],hoar:[]};
for(const d of W.MON_DEFS) groups[landOfZone(W.defZone(d))].push(d);

function mobsDoc(){
  const nBoss=W.BOSS_DEFS.length, helpers=W.BOSS_DEFS.flatMap(b=>[b.add,b.totem,b.prop].filter(Boolean));
  const total=W.MONS.length;
  let s=HEADER('Monsters: every mob and its stats','Every monster kind in the game, with the numbers the server uses and the place in the code that defines it. Dungeons (docs/DUNGEONS.md) draw their mobs from here (section 11). **Every number is a base stat (zone tier 0)**: a zone tier, and so a dungeon played at a tier, only multiplies them (`zoneTierK` in src/shared/tiers.js: +10 levels per tier); tiered values are not listed.');
  s+=`${W.MON_DEFS.length} monster kinds in ${W.ZONES.filter(z=>!z.boss&&W.MON_DEFS.some(d=>W.defZone(d)===z)).length} zones, ${nBoss} bosses, ${helpers.length} boss helpers (summons and props) and ${W.GREY_DEFS.length} grey-veined quest monsters: ${W.ALL_MON_DEFS.length} definitions, plus ${Object.keys(W.DG_BOSS_DEFS).length} dungeon bosses with their helpers (section 11). ${total} monsters exist in the world at start (${W.MON_DEFS.length} kinds in their camps + ${nBoss} bosses).\n\n`;

  s+='## 1. Where it is defined\n\n'+rowsOf(['What','Where'],[
    ['Every monster kind (one row each: id, name, level, element, model, scale, look flags `pal`, tuning `hpK` / `dmgPct` / `count` / `zone`)',code('MON_DEFS')+' '+loc(MON_DEF_FILE,/^const MON_DEFS=/)],
    ['Family defaults a row inherits (health toughness `hpK`, damage share `dmgPct`, attack interval `atk`, `speed`, `rad`, `height`, `aggro`, `per`: camp size - 2)',code('FAM')+' '+loc(MON_DEF_FILE,/^const FAM=/)],
    ['How HP, damage and XP are made from the level (also used by zone tiers and by anything that wants a monster at another level)',code('defAt')+' '+loc(MON_DEF_FILE,/^function defAt/)+', '+code('prepDef')+' '+loc(MON_DEF_FILE,/^function prepDef/)],
    ['The level formulas (expected player damage / health, armour cut, XP, coins)',code('expDmg')+' / '+code('expHP')+' / '+code('xpFor')+' / '+code('coinsFor')+' '+loc(SH+'balance.js',/^const expDmg=/)+'-'+lineOf(SH+'balance.js',/^const coinsFor=/)],
    ['The six bosses, their move set (`kit`), arena, summons (`add`), props, boss-bar texts',code('BOSS_DEFS')+' '+loc(MON_DEF_FILE,/^const BOSS_DEFS=/)],
    ['The grey-veined monsters of the main quest',code('GREY_DEFS')+' '+loc(MON_DEF_FILE,/^const GREY_DEFS=/)],
    ['Every definition in one list (what `DEF_BY_ID` on the server indexes)',code('ALL_MON_DEFS')+' '+loc(MON_DEF_FILE,/^const ALL_MON_DEFS=/)],
    ['How many of each kind exist, and where their camps are (a zone holds 40 of the level-1 kind down to 20 of level 15; the vale and the Reach 12 of each; `count` overrides)',code('MON_COUNT')+' '+loc(SV+'monsters.js',/^const MON_COUNT=/)+', '+code('initMonstersS')+' '+loc(SV+'monsters.js',/^function initMonstersS/)],
    ['Zones (name, level, where): home rings and edges / the Sakura Vale / the Hoarfrost Reach / the Tide King\'s beach',code('ZONES')+' '+loc(SH+'zones.js',/^const ZONES=/)+', '+loc(SH+'vale.js',/^const ARENAS=/)+', '+loc(SH+'hoarfrost.js',/^for\(const A of \[ARENA26/)+', '+loc(SH+'beach.js',/ZONES\.push\(ARENA_TIDE/)],
    ['Monster behaviour (aggro, chase, attack, leash, wander, respawn)',code('updateMonstersS')+' '+loc(SV+'monsters.js',/^function updateMonstersS/)],
    ['What a kill pays (XP, coins, an item roll, the material, quests, boss skills)',code('rewardKill')+' '+loc(SV+'combat.js',/^function rewardKill/)],
    ['Materials a kind drops (one per kind, `MAT_NAMES`)',code('MATS')+' '+loc(SH+'drops.js',/^const MAT_NAMES=/)],
    ['What a zone tier does to a monster (+10 levels per tier)',code('zoneTierK')+' '+loc(SH+'tiers.js',/^function zoneTierK/)+', '+code('monK')+' '+loc(SV+'tiers.js',/^const monK=/)],
    ['Boss fights: engagement, phases, reset / one move set per boss / the move primitives',code('BOSSES')+' '+loc(SV+'boss.js',/^const BOSSES=/)+' / '+code('BOSS_KITS')+' '+loc(SV+'boss-fx.js',/^const BOSS_KITS=/)+' / '+SV+'boss-fx.js'],
    ['The boss notices on the quest board',code('BOSS_QUESTS')+' '+loc(SH+'quests.js',/^const BOSS_QUESTS=/)],
    ['The dungeon bosses and their helpers (made on demand in a run\'s round hall, not in `BOSS_DEFS`)',code('DG_BOSSES')+' '+loc(SH+'dungeons/bosses.js',/^const DG_BOSSES=/)+', '+code('DG_BOSS_DEFS')+' (same file), move sets '+loc(SV+'dungeons/boss-kits.js',/^BOSS_KITS\.spore=/)],
    ['Which kinds a dungeon uses (`mobs.walkers`, `mobs.guardians`: ids of `MON_DEFS`), its land, entrance zone, boss and level',code('defineDungeonTheme')+' '+loc(SH+'dungeons.js',/^function defineDungeonTheme/)+', one file per theme in src/shared/dungeons/themes/'],
    ['How a run spawns a monster at its level with the party\'s health (elites, no respawn)',code('dgSpawnS')+' '+loc(SV+'dungeons/mobs.js',/^function dgSpawnS/)+', '+code('dgKOf')+' '+loc(SV+'dungeons/mobs.js',/^function dgKOf/)+', '+code('dgParty')+' '+loc(SH+'dungeons.js',/^const dgParty=/)],
    ['How each model looks (client)','see section 13']])+'\n';

  s+='\n## 2. How the numbers are made\n\n'+
`Let L be the monster's level and \`f(L) = L + (13/12)^L\`.

- **HP** = round(expDmg(L) × (4 + 0.45 L) × hpK × highMult(L)): the hits a same-level, normally geared player needs, times how tough the kind is. \`highMult\` is 1.5 from level ${10} up. A boss or prop has a fixed hit count instead (\`d.hits\`: 70 for a boss, 9 for a prop). \`expDmg(L) = 3 f(L) + TIER_ATK[tierFor(L)]\`.
- **Dmg** (per hit, before the player's armour) = round(expHP(L) × dmgPct / (1 − expRed(L))): a share of a same-level player's health. A boss uses 16%. \`expHP(L) = 20 f(L) + setHP(tierFor(L))\`. Armour then cuts damage by \`def / (def + 60)\`, soft-capped above 60% (defense 90) toward 90% (\`defRed\`, src/shared/balance.js).
- **XP** = xpFor(L) = f(L) × 1.15^(L−5) × highMult (a boss ×25, a prop 0; above level 60 the pay keeps its level-60 rate and doubles every 10 levels, \`PAY_LV\` in src/shared/balance.js, so zone tiers IV and V stay sane). **Coins** per kill = round(f(L) × U(1.5, 2.5) × 1.1^(L−5) × highMult); the tables show the mean (boss ×20).
- **A kill never pays for more than 10 levels above you** (\`xpLeadK\`, \`XP_LEAD\` in src/shared/balance.js): the XP is that of a monster of level min(its level, yours + 10), so a zone tier or a dungeon difficulty that makes a monster stronger than that pays no more XP (coins and drops go on rising). **Level 50 is a soft cap**: every level from 50 on costs ×1.5 the one before (\`expToNext\`, \`LV_SOFT_GROWTH\`).
- **Hits** in the tables is HP / expDmg(L): how many hits of a same-level, normally geared player it takes.
- **Behaviour**: attack every \`Atk s\` seconds with a 0.28 s wind-up; moves at \`Spd\` m/s; a monster with \`Aggro 0\` ("passive") leaves you alone until hit; it gives up when 32 m from its camp; it only thinks while a player is within 110 m; a dead one respawns after 35 s if nobody is within 22 m of its camp. Bosses engage when a player steps inside their arena and reset when nobody is left inside.
- **Level debuff**: ±5% damage per level of difference between player and monster. **Zone tiers** add 10 levels per tier to every monster of a land, and to a dungeon played at that land's tier (see \`zoneTierK\`); the tables show base values only.
- **Drops**: every kind drops its material with ${W.DROP_CHANCE*100}% (one, sometimes two); a boss always drops ${W.BOSS_DROPS}. An item roll on every kill (monster: 2% common, 0.5% rare, 0.1% epic; boss: 50 / 10 / 3 / 1 / 0.1% common to legendary) of the gear tier of the monster's level (\`tierFor\`, see docs/EQUIPMENT.md). Each boss skill drops from its boss with ${W.BOSS_SKILL_CHANCE*100}% per kill and helper.

`;

  const section=(n,title,note,defs)=>`## ${n}. ${title}\n\n${note}\n\n${monTable(defs)}\n\n`;
  s+='## 3. Reading the tables\n\n**Lv** level; **El** element (`—` = none); **HP** health in the def\'s own units; **Hits** HP / a same-level player\'s damage; **Dmg** damage per hit before armour; **Atk s** seconds between attacks; **Spd** metres per second; **Aggro** distance at which it notices you; **XP** and **Coins** per kill (mean) at base (tier 0); **Count** how many exist; **Drop** its material; **Model** the client model and `scale`; **Defined** file:line of its row.\n\n';
  s+=section(4,'Home forest: the three rings (levels 1-15)','Zones are named by level; ring 0 = levels 1-6, ring 1 = 7-11, ring 2 = 12-15 around the village.',groups.ring);
  s+=section(5,'Home forest: the edges (levels 16-20)','Side content with its own `zone` and `count` (the shore, the Sunwall\'s foot, the Greyspine foothills).',groups.edge);
  s+=section(6,'Sakura Vale (levels 16-25)','Two kinds per level, 12 of each, in ten zones.',groups.vale);
  s+=section(7,'Hoarfrost Reach (levels 22-30)','Two kinds per level, 12 of each, in nine zones.',groups.hoar);

  s+='## 8. Bosses (6)\n\nHealth is 70 hits of a same-level player (×1.5 from level 10); a hit is 16% of that player\'s health. Each boss has its own move set on top of the shared melee and the phases at 60% and 30% (`server/boss.js`).\n\n';
  s+=rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','XP','Coins','Material','Arena','Summons','Prop','Music','Move set','Defined'],W.BOSS_DEFS.map(b=>{
    const d=b.def, L=d.level;
    return [code(d.id),d.name,L,d.el,d.hp,d.dmg,d.atk,d.speed,num(d.xp),coinsAvg(d,L),W.MATS[d.id].name,zoneOf(d,b.arena),b.add?b.add.name:'—',b.prop?b.prop.name:b.totem?b.totem.name:'—',d.music||'boss'+L,
      code(b.kit)+' '+loc(SV+'boss-kits-'+(['roots','tide'].includes(b.kit)?'home':['oni','kitsune'].includes(b.kit)?'vale':'north')+'.js',new RegExp('^BOSS_KITS\\.'+b.kit+'=')),defRef(d)];
  }))+'\n\n';
  s+='Boss quest notices (`BOSS_QUESTS`, '+loc(SH+'quests.js',/^const BOSS_QUESTS=/)+'): '+W.BOSS_QUESTS.map(q=>`${q.title} from level ${q.from}`).join('; ')+'.\n\n';
  s+='### Boss skills (36: a skill and a burst for each class, each with a 10% drop chance per kill)\n\nRows `drop:\'<boss id>\'` at the end of `SKILLS` ('+loc(SH+'classes.js',/^const SKILLS=\{/)+' ...), listed by `BOSS_SKILLS` ('+loc(SH+'drops.js',/^const BOSS_SKILL_CHANCE/)+').\n\n';
  const skRows=[]; for(const b of W.BOSS_DEFS) for(const id of W.BOSS_SKILLS[b.def.id]||[]){ const k=W.SKILLS[id]; skRows.push([b.short,code(id),k.name,W.CLASSES[k.cls].name,k.slot,k.el||'—',k.lv,k.cd+' s',loc(SH+'classes.js',new RegExp('^\\s*'+id+":\\{cls:.*drop:'"))]); }
  s+=rowsOf(['Boss','Id','Skill','Class','Slot','El','Lv','Cooldown','Defined'],skRows)+'\n\n';

  s+='## 9. Boss helpers: summons and props\n\nSummoned by a boss kit or placed by it; not in `MON_DEFS`, so no camps, no quest-board notices and no material. They are in `ALL_MON_DEFS`.\n\n';
  s+=rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','Aggro','XP','Role','Defined'],W.BOSS_DEFS.flatMap(b=>[['add',b.add],['totem',b.totem],['prop',b.prop]].filter(r=>r[1]).map(([kind,d])=>[code(d.id),d.name,d.level,d.el||'—',d.hp,d.noAttack?'—':d.dmg,d.noAttack?'—':d.atk,d.speed||'—',d.aggro?d.aggro+' m':'—',d.noXp?'—':num(d.xp),(kind==='add'?'summoned by ':kind==='totem'?'shield-phase totem of ':'shelter prop of ')+b.short,defRef(d)])))+'\n\n';

  s+='## 10. Grey-veined monsters (main quest)\n\nTougher copies of a zone\'s kind (`greyDef`, tripled XP). Not in `MON_DEFS`: the server spawns a few for each player on that quest step (`server/main-quest.js`).\n\n'+
    rowsOf(MON_HEAD,W.GREY_DEFS.map(monRow))+'\n\n';

  {
    const DB=W.DG_BOSS_DEFS, DBF=SH+'dungeons/bosses.js', ids=Object.keys(DB), themes=Object.values(W.DG_THEMES).filter(t=>!t.dev);
    const dbRef=id=>loc(DBF,new RegExp("\\bid:'"+id+"'")), themeName=id=>W.DG_THEMES[id]?W.DG_THEMES[id].name:'—';
    const kitFile=SV+'dungeons/boss-kits.js';
    s+='## 11. Dungeons: bosses, their helpers and the mob pools\n\n'+
      `A dungeon (\`src/shared/dungeons/themes/<id>.js\`) is built from the world's own monster kinds (its \`mobs.walkers\` and \`mobs.guardians\`, the rows of sections 4-7: base stats there) spawned at the run's level (**${W.DG_LV}**) with the party's health factor; an elite has ×${W.DG_ELITE_HP} health and is a quarter bigger; nothing respawns. Its boss is one of the ${ids.length} below, made on demand in a round hall. All numbers are base stats (\`hits\` 70, level ${W.DG_LV}, like a world boss); how a run scales them is in docs/DUNGEONS.md.\n\n`;
    s+='### 11.1 Dungeon bosses ('+ids.length+')\n\n'+rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','XP','Coins','Dungeon','Clear pays','Summons','Prop','Music','Move set','Defined'],ids.map(id=>{
      const b=DB[id], d=b.def, L=d.level, R=W.DG_REWARDS[b.dungeon];
      return [code(d.id),d.name,L,d.el,d.hp,d.dmg,d.atk,d.speed,num(d.xp),coinsAvg(d,L),themeName(b.dungeon),R?(R.kind==='weapon'?'a level-30 weapon':R.kind==='armor'?'a level-30 armour piece':'a level-30 ring'):'—',b.add?b.add.name:'—',b.prop?b.prop.name:'—',d.music||'boss'+L,
        code(b.kit)+' '+loc(kitFile,new RegExp('^BOSS_KITS\\.'+b.kit+'=')),dbRef(d.id)];
    }))+'\n\n';
    s+='### 11.2 Dungeon boss helpers (summons and props)\n\nNot in `MON_DEFS`: made by the boss kit.\n\n'+rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','XP','Role','Defined'],ids.flatMap(id=>{
      const b=DB[id]; return [['add',b.add],['prop',b.prop]].filter(r=>r[1]).map(([kind,d])=>[code(d.id),d.name,d.level,d.el||'—',d.hp,d.noAttack?'—':d.dmg,d.noAttack?'—':d.atk,d.speed||'—',d.noXp?'—':num(d.xp),(kind==='add'?'summoned by ':'prop of ')+b.short,dbRef(d.id)]);
    }))+'\n\n';
    const named=list=>list.length?list.map(mid=>{ const d=W.ALL_MON_DEFS.find(x=>x.id===mid); return d.name+' ('+d.level+')'; }).join(', '):'—';
    s+='### 11.3 Mob pools of each dungeon\n\n`walkers` fit the 4 m doors and roam the whole dungeon; `guardians` are the big ones that stay in their room. Levels in brackets are the kinds\' own; in the run they are spawned at level '+W.DG_LV+'.\n\n'+rowsOf(['Dungeon','Id','Land','Entrance zone','Lv','Walkers','Guardians','Boss','Music','Defined'],themes.map(t=>[t.name,code(t.id),(W.DG_LANDS[t.land]||{name:t.land}).name,t.at,t.lv,named(t.mobs.walkers),named(t.mobs.guardians),W.DG_BOSS_DEFS[t.boss]?W.DG_BOSS_DEFS[t.boss].def.name:t.boss,t.music||'—',loc('src/shared/dungeons/themes/'+t.id+'.js',/^\s*mobs:\{walkers/)]))+'\n\n';
  }
  s+='## 12. Level table\n\nThe expected numbers at each level (a same-level player in the gear of their tier, a monster with `hpK` 1): what a dungeon mob at level L would get from `defAt`.\n\n';
  const lv=[]; for(let L=1;L<=W.MAX_ZONE_LV;L++){
    const kills=W.expToNext(L)/W.xpFor(L);
    lv.push([L,num(W.fLv(L)),Math.round(W.expDmg(L)),Math.round(W.expHP(L)),Math.round(W.expRed(L)*100)+'%','T'+(W.tierFor(L)+1),Math.round(W.expDmg(L)*(4+0.45*L)*W.highMult(L)),Math.round(W.expHP(L)*0.10/(1-W.expRed(L))),num(W.xpFor(L)),Math.round(W.expToNext(L)),Math.round(kills),Math.max(1,Math.round(W.fLv(L)*2*Math.pow(1.1,Math.max(0,L-5))*W.highMult(L)))]);
  }
  s+=rowsOf(['L','f(L)','Player dmg','Player HP','Armour cut','Gear tier','Mob HP (hpK 1)','Mob dmg (10%)','XP / kill','XP to next','Kills / level','Coins / kill'],lv)+'\n\n';
  s+='Formulas: '+code('fLv')+' '+loc(SH+'balance.js',/^const fLv=/)+', '+code('tierFor')+' '+loc(SH+'balance.js',/^const tierFor=/)+', '+code('expToNext')+' '+loc(SH+'balance.js',/^const expToNext=/)+' (from level 25 a level costs as many same-level kills as 25 → 26 does).\n\n';

  s+='## 13. Client models\n\nA def\'s `model` picks a family model (`MODELS.<model>={geo,build,anim}`) and its `pal` flags pick the variant (see CLAUDE.md section 4). `FAM` gives each family\'s defaults.\n\n';
  const files=fs.readdirSync(path.join(ROOT,GC)).filter(f=>/^monster-.*\.js$/.test(f)), modelAt={};
  for(const f of files) srcLines(GC+f).forEach((l,i)=>{ const m=/^MODELS\.(\w+)=/.exec(l); if(m) modelAt[m[1]]=GC+f+':'+(i+1); });
  s+=rowsOf(['Model','Kinds using it','Family defaults (hpK / dmgPct / atk s / speed / rad / height / aggro / camp)','Family row','Client model'],Object.keys(W.FAM).map(k=>{
    const F=W.FAM[k], n=W.ALL_MON_DEFS.filter(d=>d.model===k).length;
    return [code(k),n,[F.hpK,F.dmgPct,F.atk,F.speed,F.rad,F.height,F.aggro,F.per+2].join(' / '),loc(MON_DEF_FILE,new RegExp('^  '+k+':\\s*\\{hpK')),modelAt[k]||'—'];
  }))+'\n';
  return s;
}

// =====================================================================  EQUIPMENT.md
const IT=SH+'items.js', BAL=SH+'balance.js';
const ALL_SLOTS_LIST=[...W.WEAPON_SLOTS,...W.ARMOR_SLOTS];
const resName=id=>(W.ORE_GRADES.concat(W.LOG_GRADES).find(g=>g[0]===id)||[id,id])[1];
function levelsOfTier(t){ const ls=[]; for(let L=1;L<=W.MAX_ZONE_LV;L++) if(W.tierFor(L)===t) ls.push(L); return ls.length?(ls.length>1?ls[0]+'-'+ls[ls.length-1]:String(ls[0])):'—'; }
const SLOT_TITLE={sword:'Sword (Warrior weapon)',bow:'Bow (Archer weapon)',wand:'Wand (Mage weapon)',helmet:'Helmet',top:'Top (chest)',bottom:'Bottom (legs)',shoes:'Shoes'};

// the worst case on one hiker, from the data: the best armour piece of every slot in the item table, Iron Will at its top level, the strongest skill buff, the best guard potion
function worstCase(){
  let def=0; for(const sl of W.ARMOR_SLOTS) def+=Math.max(...Object.values(W.ITEM).filter(i=>i.kind==='armor'&&i.slot===sl).map(i=>i.def));
  const gear=W.defRed(def), iron=W.passiveValue('ironwill',W.SKILL_MAX_LV), buff=Math.max(...Object.values(W.SKILLS).map(k=>k.buff&&k.buff.red||0)), pot=Math.max(...W.POT_BUFF);
  const withIron=1-(1-gear)*(1-iron), plain=1-(1-gear)*(1-iron)*(1-buff)*(1-pot), all=1-Math.max(W.DMG_TAKEN_MIN,1-plain);
  const pc=n=>(n*100).toFixed(1)+'%';
  return {def,text:`The worst case on one hiker, worked out from the data: the best piece of every slot (${def} defense) negates ${pc(gear)}; Iron Will (${pc(iron)}) makes it ${pc(withIron)}; the strongest skill buff (${pc(buff)}) and the best guard potion (${pc(pot)}) on top would make it ${pc(plain)} by plain multiplication, and the floor holds it at ${pc(all)}. Nothing in the game reaches 100%: armour never passes ${Math.round(W.RED_CAP*100)}%, the sum of all sources never passes ${Math.round((1-W.DMG_TAKEN_MIN)*100)}%, and a hit always does at least 1.`};
}
function equipmentDoc(){
  let s=HEADER('Equipment: every piece of gear and tool','Every item in `ITEM`: 7 pieces × 6 level tiers × 5 rarities = 210 pieces of gear, the 90 profession tools, and the '+W.dgAllIds().length+' level-30 dungeon pieces and rings (section 7), with the numbers the server uses and where they are defined.');

  s+='## 1. Where it is defined\n\n'+rowsOf(['What','Where'],[
    ['Every item (generated in two loops from the arrays below): `ITEM`, `ITEM_LIST` (gear: 210), `TOOL_LIST` (tools: 90, in `ITEM` but not in `ITEM_LIST`)',code('ITEM')+' '+loc(IT,/^const ITEM=\{\}/)],
    ['Names of every piece and tier',code('SLOT_NAMES')+' '+loc(IT,/^const SLOT_NAMES=/)],
    ['Level a tier needs',code('TIER_LV')+' '+loc(IT,/^const TIER_LV=/)],
    ['Weapon attack by tier',code('TIER_ATK')+' '+loc(BAL,/^const TIER_ATK=/)],
    ['Armour health and defense by tier and piece',code('ARMOR_HP')+' '+loc(BAL,/^const ARMOR_HP=/)+', '+code('ARMOR_DEF')+' '+loc(BAL,/^const ARMOR_DEF=/)],
    ['Which tier drops at which monster level',code('tierFor')+' '+loc(BAL,/^const tierFor=/)],
    ['Rarities and their multiplier',code('RARITY')+' '+loc(IT,/^const RARITY=/)+', '+code('RAR_MULT')+' '+loc(IT,/^const RAR_MULT=/)],
    ['Base prices (tier) and weight of each piece',code('PRICE')+' '+loc(IT,/^const PRICE=/)+', '+code('SLOT_PRICE')+' '+loc(IT,/^const PRICE=/)],
    ['The item id scheme (`sword2`, `sword2-e`)',code('itemId')+' '+loc(IT,/^const itemId=/)],
    ['Tools (pickaxe, axe, sickle): materials, prices, double-yield chance by rarity',code('TOOL_MAT')+' / '+code('TOOL_PRICE')+' / '+code('TOOL_EXTRA')+' '+loc(IT,/^const TOOL_MAT=/)+'-'+lineOf(IT,/^const TOOL_PRICE=/)],
    ['What gear adds to a player (health, attack, defense)',code('gearStatsOf')+' '+loc(IT,/^function gearStatsOf/)+', '+code('recalcP')+' '+loc(SV+'players.js',/^function recalcP/)],
    ['How much damage armour negates (soft-capped at 90%) and the 10% floor on a hit',code('defRed')+' '+loc(BAL,/^const defRed=/)+', '+code('hurtP')+' '+loc(SV+'players.js',/^function hurtP/)],
    ['Wearing an item (level check, slot)',code('equipP')+' '+loc(SV+'economy.js',/^function equipP/)],
    ['Shops: common items only, +20% per copy bought',code('buyP')+' '+loc(SV+'economy.js',/^function buyP/)+', '+code('shopPrice')+' '+loc(IT,/^const SHOP_STEP/)+', shop panel '+loc('src/game/economy/shops.js',/ITEM_LIST\.filter\(i=>ofKind/)],
    ['Monster and boss drops (the item roll and its tier)',code('rollMonsterRarity')+' / '+code('rollBossRarity')+' '+loc(IT,/^function rollMonsterRarity/)+', used in '+code('rewardKill')+' '+loc(SV+'combat.js',/^function rewardKill/)],
    ['Quest board rewards (item rarity)',code('rollQuestItemRarity')+' '+loc(SH+'quests.js',/(function|const) rollQuestItemRarity/)],
    ['Merging three identical items into the next rarity (Greta\'s forge)',code('mergeP')+' '+loc(SV+'economy.js',/^function mergeP/)+', '+code('mergedId')+' '+loc(IT,/^const mergedId/)],
    ['Crafting from ore / logs (rarity common to epic)',code('craftCost')+' '+loc(SH+'crafting.js',/^function craftCost/)+', '+code('craftP')+' '+loc(SV+'crafting.js',/^function craftP/)],
    ['The level-30 dungeon pieces and rings: stats, ids, rewards, enhancing',code('dgItem')+' '+loc(SH+'dungeon-rewards.js',/^function dgItem/)+', registered in `ITEM` by '+loc(SH+'dungeon-items.js',/^for\(const id of dgAllIds\(\)\)/)+'; the drop of the Tempering Stone and tempering '+code('dgTemperP')+' '+loc(SV+'dungeon-gear.js',/^function dgTemperP/)],
    ['How a piece looks on the character',code('ARMOR_LOOK')+' '+loc(IT,/^const ARMOR_LOOK=/)],
    ['The inventory icon of every piece and tool',loc('src/game/ui/item-icons.js',/^\/\/@/)+' (the file)'],
    ['A save\'s gear (what is worn, what is in the bag)',code('newGearFor')+' '+loc(IT,/^function newGearFor/)+', '+code('sanitizeGear')+' '+loc(SV+'players.js',/^function sanitizeGear/)]])+'\n';

  s+='\n## 2. How the stats are made\n\n'+
`- **Weapon attack** = round(TIER_ATK[tier] × RAR_MULT[rarity]). The weapon you wield sets your class (sword: Warrior, bow: Archer, wand: Mage). A player's damage is \`(3 f(L) + gear attack) × (1 + symbol)\`.
- **Armour health** = round(ARMOR_HP[piece][tier] × RAR_MULT[rarity]); **defense** = max(ARMOR_DEF[piece][tier] + rarity, round(ARMOR_DEF × RAR_MULT)). A player's health is \`(20 f(L) + gear health) × (1 + passives) × (1 + symbol)\`; damage taken is cut by \`def / (def + 60)\` up to 60% negation (defense 90) and then softly capped toward 90% (\`defRed\`): the maxed level-30 set (576 defense) negates 84%, not 91%; a hit always does at least 10% (\`DMG_TAKEN_MIN\`). ${worstCase().text}
- **Price** = round(PRICE[tier] × SLOT_PRICE[piece] × 3^rarity); sells for 40% (\`sellPrice\`). Only **common** items are in the shops, unlimited, each copy bought costs 20% of the base more until sunrise.
- **Level**: an item needs \`lv\` = TIER_LV[tier] (${W.TIER_LV.join(', ')}) to be worn. Tiers 1-4 are the home forest's, 5-6 the Sakura Vale's samurai gear; **tier 6 is the top of the world's gear**: levels 25-30 (the Hoarfrost Reach) still drop tier 6; the level-30 dungeon pieces (section 7) are a tier above and only dungeons pay them.
- **Rarity** (${W.RARITY.map((r,i)=>r+' ×'+W.RAR_MULT[i]).join(', ')}): ${W.MERGE_COUNT} identical items merge into one of the next rarity at the forge (same tier needed). Drops: a monster 2% common, 0.5% rare, 0.1% epic per kill; a boss 50 / 10 / 3 / 1 / 0.1% (common to legendary). The rarity is rolled first, then one of the seven pieces with equal chance, of the tier of the monster's level (\`tierFor\`).
- **Crafting** makes common, rare and epic pieces only (unique and legendary come from drops and merging); a tier's weapons cost ore, its armour logs, plus 10% of the price in coins.
- Id scheme: \`<piece><tier 1-6>[-r|-e|-u|-l]\`: \`sword2\` is a common Iron Longsword, \`sword2-e\` the epic one.

`;

  s+='## 3. The six tiers\n\n'+rowsOf(['Tier','Level','Dropped at monster levels','Weapon attack (common)','Helmet HP / DEF','Top HP / DEF','Bottom HP / DEF','Shoes HP / DEF','Full set HP','Full set DEF','Base price'],
    W.TIER_LV.map((lvl,t)=>['T'+(t+1),lvl,levelsOfTier(t),W.TIER_ATK[t],...W.ARMOR_SLOTS.map(sl=>W.ARMOR_HP[sl][t]+' / '+W.ARMOR_DEF[sl][t]),W.setHP(t),W.setDef(t),W.PRICE[t]]))+'\n\n';
  s+=rowsOf(['Tier','Sword','Bow','Wand','Helmet','Top','Bottom','Shoes'],W.TIER_LV.map((lvl,t)=>['T'+(t+1),...ALL_SLOTS_LIST.map(sl=>W.SLOT_NAMES[sl][t])]))+'\n\n';
  s+='## 4. Rarities\n\n'+rowsOf(['Rarity','Suffix','Stat multiplier','Price multiplier','Monster drop','Boss drop','Crafted','Tool double-yield chance'],
    W.RARITY.map((r,i)=>[r,i?code('-'+W.RAR_KEY[i]):'(none)','×'+W.RAR_MULT[i],'×'+Math.pow(3,i),['2%','0.5%','0.1%','—','—'][i],['50%','10%','3%','1%','0.1%'][i],i<=W.CRAFT_MAX_RAR?'yes':'no','+'+Math.round(W.TOOL_EXTRA[i]*100)+'%']))+'\n\n';

  s+='## 5. Every piece of gear (210)\n\nOne table per slot, in the order tier, then rarity. **Price** is the item\'s value (the shop price of the first common copy; rarer items are not sold), **Sell** what a shop pays, **Craft** the cost at the smith or armourer (ore for weapons, logs for armour; `—` where it cannot be crafted). **Ref** is the entry of `SLOT_NAMES` the name comes from.\n\n';
  let n=0;
  for(const slot of ALL_SLOTS_LIST){
    const weapon=W.WEAPON_SLOTS.includes(slot), items=W.ITEM_LIST.filter(i=>i.slot===slot);
    s+=`### 5.${++n} ${SLOT_TITLE[slot]}\n\nNames: ${code('SLOT_NAMES.'+slot)} ${loc(IT,new RegExp('^\\s*'+slot+':\\['))}; stats: ${weapon?code('TIER_ATK')+' '+loc(BAL,/^const TIER_ATK=/):code('ARMOR_HP.'+slot)+' / '+code('ARMOR_DEF.'+slot)+' '+loc(BAL,/^const ARMOR_HP=/)+', '+loc(BAL,/^const ARMOR_DEF=/)}${weapon?'':'; look: '+code('ARMOR_LOOK.'+slot)+' '+loc(IT,new RegExp('^\\s*'+(slot==='helmet'?'helmet':slot)+':\\[\\{',''))}.\n\n`;
    s+=rowsOf(['Id','Name','Req Lv','Rarity',...(weapon?['Attack']:['Health','Defense']),'Price','Sell','Craft','Ref'],items.map(it=>{
      let cr='—'; if(it.rar<=W.CRAFT_MAX_RAR){ const c=W.craftCost(slot,it.tier,it.rar); cr=c.n+' × '+resName(c.res)+' + '+c.coins+' c'; }
      return [code(it.id),it.name,it.lv,W.RARITY[it.rar],...(weapon?[it.atk]:[it.hp,it.def]),it.price,W.sellPrice(it),cr,'SLOT_NAMES.'+slot+'['+it.tier+']'];
    }))+'\n\n';
  }

  s+='## 6. Profession tools (90)\n\nThree tool slots (`eq.pick`, `eq.axe`, `eq.sickle`), the same 6 tiers and 5 rarities as gear but **no combat stats**: the tier decides which resource nodes it can work (a node needs a tool of tier `need` or better) and the rarity how often a node gives a double yield. Bought (common only) at a Wayfarers\' Lodge, merged at the forge. Defined in `items.js` ('+loc(IT,/^const TOOL_SLOTS=/)+'), not part of `ITEM_LIST`.\n\n';
  s+=rowsOf(['Ids (common, rare, epic, unique, legendary)','Name (common)','Req Lv','Works nodes of tier','Profession','Price C / R / E / U / L','Ref'],W.TOOL_SLOTS.flatMap(slot=>W.TIER_LV.map((lvl,t)=>{
    const base=slot+(t+1);
    return [W.RAR_KEY.map(k=>code(base+(k?'-'+k:''))).join(', '),W.TOOL_MAT[t]+' '+W.TOOL_KIND[slot],lvl,'T'+(t+1),W.TOOL_PROF[slot],W.RARITY.map((r,i)=>Math.round(W.TOOL_PRICE[t]*Math.pow(3,i))).join(' / '),'TOOL_MAT['+t+'], TOOL_PRICE['+t+']'];
  })))+'\n';
    s+='\n## 7. Level-30 dungeon gear and rings ('+W.dgAllIds().length+' ids)\n\n';
  { const DR=SH+'dungeon-rewards.js', allIds=W.dgAllIds(), rare=r=>W.DG_REWARD_W[r]/10;
    s+=`A tier above the six of section 3, paid **only by dungeons**: level ${W.DG_GEAR_LV} (\`DG_GEAR_LV\`), not in \`TIER_LV\` / \`ITEM_LIST\`, so shops, drops, "give every item" and \`tierFor\` never see them (they are in \`ITEM\` and carry \`dg:true\`). 7 pieces and 7 rings, 5 rarities each, each of them enhanced from +0 up to **+${W.ENH_MAX.join(' / +')}** (by rarity): ${W.dgAllIds().length} ids. ${W.ENH_NAME}s raise a piece one step (step n costs n stones) and add ${W.ENH_STEP*100}% of its own stats per step; they drop from normal monsters of level ${W.ENH_LV}+ at ${W.ENH_DROP*100}% instead of equipment. One clear of a dungeon pays one random piece of its pool: the rarity is ${W.RARITY.map((n,r)=>n+' '+rare(r)+'%').join(', ')}, then one kind of the pool with equal chance; everyone in the party gets the same piece.\n\n`;
    s+=`Ids: \`<piece>7[-r|-e|-u|-l][+n]\` (\`sword7-e+3\` is an epic level-30 sword at +3) and \`ring-<element>[-r|-e|-u|-l][+n]\` (\`ring-fire-l+10\`). The tables list the **+0 base of each of the ${W.WEAPON_SLOTS.length+W.ARMOR_SLOTS.length+W.RING_ELS.length*1} kinds × 5 rarities** and, in the last stat column, the stat at every step from +0 to the rarity's maximum, so every id is covered. A ring adds a share of **your weapon's attack** and only when its element is your soul's (\`basic\` is the plain ring, for an unbound soul).\n\n`;
    const where=kind=>{ const t=Object.keys(W.DG_REWARDS).find(k=>W.DG_REWARDS[k].pool.includes(kind)); return t&&W.DG_THEMES[t]?W.DG_THEMES[t].name:'—'; };
    const stat=it=>it.kind==='weapon'?String(it.atk):it.kind==='armor'?it.hp+'/'+it.def:(it.pct*100).toFixed(1)+'%';
    const table=(kinds,head,mk,idOf,nameRef)=>{
      const rows=[]; for(const kind of kinds) for(let r=0;r<5;r++){
        const b=W.dgItem(idOf(kind,r,0)), steps=[]; for(let n=0;n<=W.ENH_MAX[r];n++) steps.push(stat(W.dgItem(idOf(kind,r,n))));
        rows.push([code(b.id),b.name,b.lv,W.RARITY[r],...mk(b),b.price,W.sellPrice(b),'+'+W.ENH_MAX[r],steps.join(', '),where(kind),nameRef(kind)]);
      }
      return rowsOf(['Id','Name','Req Lv','Rarity',...head,'Price','Sell','Max','Stat at +0, +1 ... +max','Paid by','Ref'],rows);
    };
    s+=`### 7.1 Weapons (${W.WEAPON_SLOTS.length*5})\n\nNames \`DG_NAMES\` ${loc(DR,/^const DG_NAMES=/)}; attack \`DG_ATK\` ${loc(DR,/^const DG_ATK=/)} × \`RAR_MULT\` × (1 + ${W.ENH_STEP} n).\n\n`+table(W.WEAPON_SLOTS,['Attack'],b=>[b.atk],(k,r,n)=>W.dgGearId(k,r,n),k=>'DG_NAMES.'+k)+'\n\n';
    s+=`### 7.2 Armour (${W.ARMOR_SLOTS.length*5})\n\nNames \`DG_NAMES\`; health \`DG_HP\` and defense \`DG_DEF\` ${loc(DR,/^const DG_ATK=/)} × the rarity and the enhancement.\n\n`+table(W.ARMOR_SLOTS,['Health','Defense'],b=>[b.hp,b.def],(k,r,n)=>W.dgGearId(k,r,n),k=>'DG_NAMES.'+k)+'\n\n';
    s+=`### 7.3 Rings (${W.RING_ELS.length*5}; the ring slot, \`eq.ring\`)\n\nNames \`RING_NAMES\` ${loc(DR,/^const RING_NAMES=/)}; a common ring adds \`RING_PCT\` = ${W.RING_PCT*100}% of the weapon's attack (× the rarity multiplier × the enhancement), shown in the stat columns.\n\n`+table(W.RING_ELS,['Share of weapon attack'],b=>[(b.pct*100).toFixed(1)+'%'],(k,r,n)=>W.dgRingId(k,r,n),k=>'RING_NAMES.'+k)+'\n';
    s+=`\nWhat each dungeon pays: ${Object.keys(W.DG_REWARDS).map(t=>(W.DG_THEMES[t]?W.DG_THEMES[t].name:t)+': '+W.DG_REWARDS[t].kind+' ('+W.DG_REWARDS[t].pool.join(', ')+')').join('; ')} (\`DG_REWARDS\` ${loc(DR,/^const DG_REWARDS=/)}; odds \`DG_REWARD_W\` ${loc(DR,/^const DG_REWARD_W=/)}; enhancing \`ENH_MAX\` / \`ENH_STEP\` / \`ENH_DROP\` ${loc(DR,/^const ENH_MAX=/)}).\n`;
  }
  return s;
}

// ---- write or check ----
const OUT={'docs/MOBS.md':mobsDoc(),'docs/EQUIPMENT.md':equipmentDoc()};
let stale=0;
const noLines=t=>t.replace(/(\.js):\d+(?:-\d+)?/g,'$1:N');
for(const f in OUT){
  const p=path.join(ROOT,f), now=fs.existsSync(p)?fs.readFileSync(p,'utf8'):null;
  if(CHECK){
    if(now===OUT[f]) console.log('ok     '+f);
    else if(now!==null&&noLines(now)===noLines(OUT[f])){ console.log('moved  '+f+' (only line numbers changed: node tools/gen-docs.js refreshes them)'); if(STRICT) stale++; }
    else { stale++; console.log('STALE  '+f+' (run node tools/gen-docs.js)'); }
  } else { fs.writeFileSync(p,OUT[f]); console.log('wrote '+f+' ('+OUT[f].split('\n').length+' lines)'); }
}
process.exit(stale?1:0);
