// Writes docs/MOBS.md (every monster and its stats) and docs/EQUIPMENT.md (every piece of gear and tool) from the live code in src/, each with the file:line
// it is defined at, so the lists cannot drift from the game. No build needed.
//   node tools/gen-docs.js          write both files
//   node tools/gen-docs.js --check  exit 1 if the DATA in either file is out of date (stats, names, counts); a file whose only difference is
//                                   that quoted line numbers moved is reported as "refs moved" and passes (editing any quoted file shifts lines);
//                                   add --strict to fail on that too. Writes nothing.
// Run it after changing monster-defs.js, items.js, balance.js, drops.js, zones, the boss kits or any file whose line number the docs quote.
const fs=require('fs'), path=require('path');
const {ROOT,loadServer}=require('./load');
const NAMES=['FAM','MON_DEFS','ALL_MON_DEFS','BOSS_DEFS','GREY_DEFS','MONS','ZONES','defZone','MATS','BOSS_SKILLS','SKILLS','CLASSES','BOSS_QUESTS','BOSS_DROPS',
  'DROP_CHANCE','BOSS_SKILL_CHANCE','MAX_ZONE_LV','ITEM_LIST','TOOL_LIST','TIER_LV','TIERS','RARITY','RAR_KEY','RAR_MULT','SLOT_NAMES','PRICE','SLOT_PRICE','TIER_ATK',
  'ARMOR_HP','ARMOR_DEF','setHP','setDef','TOOL_MAT','TOOL_PRICE','TOOL_EXTRA','TOOL_KIND','TOOL_PROF','TOOL_SLOTS','craftCost','ORE_GRADES','LOG_GRADES','sellPrice',
  'CLASS_OF','WEAPON_SLOTS','ARMOR_SLOTS','MERGE_COUNT','SHOP_STEP','CRAFT_MAX_RAR','tierFor','fLv','expDmg','expHP','expRed','xpFor','expToNext','highMult','defRed'];
const {x:W}=loadServer({send(){},broadcast(){}},NAMES);
const CHECK=process.argv.includes('--check'), STRICT=process.argv.includes('--strict');

// ---- finding where things are defined (1-based line numbers, so the docs quote file:line) ----
const cache={};
const srcLines=f=>cache[f]||(cache[f]=fs.readFileSync(path.join(ROOT,f),'utf8').split('\n'));
function lineOf(f,re){ const i=srcLines(f).findIndex(l=>re.test(l)); if(i<0) throw new Error('gen-docs: nothing in '+f+' matches '+re); return i+1; }
const loc=(f,re)=>f+':'+lineOf(f,re);
const SH='src/shared/', SV='src/server/', GC='src/game/combat/';
const rowsOf=(headers,rows)=>['| '+headers.join(' | ')+' |','|'+headers.map(()=>'---').join('|')+'|',...rows.map(r=>'| '+r.join(' | ')+' |')].join('\n');
const num=n=>Number.isInteger(n)?String(n):n.toFixed(1);
const code=s=>'`'+s+'`';
const upper=s=>s[0].toUpperCase()+s.slice(1);
const HEADER=(name,about)=>'# '+name+'\n\n<!-- generated by node tools/gen-docs.js: do not edit by hand, change the code and run it again -->\n'+about+'\n\n'+
  'Generated from the live code by `node tools/gen-docs.js` (`--check` tells you when this file is out of date). Line numbers are those of the code when it was generated.\n\n';

// =====================================================================  MOBS.md
const MON_DEF_FILE=SH+'monster-defs.js';
const coinsAvg=(d,L)=>Math.max(1,Math.round(W.fLv(L)*2*Math.pow(1.1,Math.max(0,L-5))*W.highMult(L)))*(d.boss?20:1);   // coinsFor(L) rolls 1.5..2.5, so 2 is its mean
const countOf=d=>W.MONS.filter(m=>m.def.id===d.id).length;
function defRef(d){ return loc(MON_DEF_FILE,d.grey?new RegExp("greyDef\\('\\w+','"+d.id+"'"):new RegExp("\\bid:'"+d.id+"'")); }
function zoneOf(d,arena){ const zn=arena?W.ZONES.find(z=>z.key===arena):W.defZone(d); return zn?zn.name:'—'; }
function landOfZone(zn){ return zn.hoar?'hoar':zn.vale?'vale':zn.ring===3?'edge':'ring'; }
const MON_HEAD=['Id','Name','Lv','El','HP','Hits','Dmg','Atk s','Spd','Aggro','XP','Coins','Count','Zone','Drop','Model','Defined'];
function monRow(d){
  const L=d.level, mat=W.MATS[d.id];
  return [code(d.id),d.name,L,d.el||'—',d.hp,num(d.hp/W.expDmg(L)),d.dmg,d.atk,d.speed,d.aggro?d.aggro+' m':'passive',num(d.xp),d.noXp?'—':coinsAvg(d,L),
    countOf(d)||'on demand',zoneOf(d),mat?mat.name:'—',d.model+' ×'+d.scale,defRef(d)];
}
const monTable=defs=>rowsOf(MON_HEAD,defs.map(monRow));
const groups={ring:[],edge:[],vale:[],hoar:[]};
for(const d of W.MON_DEFS) groups[landOfZone(W.defZone(d))].push(d);

function mobsDoc(){
  const nBoss=W.BOSS_DEFS.length, helpers=W.BOSS_DEFS.flatMap(b=>[b.add,b.totem,b.prop].filter(Boolean));
  const total=W.MONS.length;
  let s=HEADER('Monsters: every mob and its stats','Every monster kind in the game, with the numbers the server uses and the place in the code that defines it. Dungeons (docs/DUNGEONS.md) draw their mobs from here. **Every number is a base stat (zone tier 0)**: a zone tier, and so a dungeon played at a tier, only multiplies them (`zoneTierK` in src/shared/tiers.js: +10 levels per tier); tiered values are not listed.');
  s+=`${W.MON_DEFS.length} monster kinds in ${W.ZONES.filter(z=>!z.boss&&W.MON_DEFS.some(d=>W.defZone(d)===z)).length} zones, ${nBoss} bosses, ${helpers.length} boss helpers (summons and props) and ${W.GREY_DEFS.length} grey-veined quest monsters: ${W.ALL_MON_DEFS.length} definitions. ${total} monsters exist in the world at start (${W.MON_DEFS.length} kinds in their camps + ${nBoss} bosses).\n\n`;

  s+='## 1. Where it is defined\n\n'+rowsOf(['What','Where'],[
    ['Every monster kind (one row each: id, name, level, element, model, scale, look flags `pal`, tuning `hpK` / `dmgPct` / `count` / `zone`)',code('MON_DEFS')+' '+loc(MON_DEF_FILE,/^const MON_DEFS=/)],
    ['Family defaults a row inherits (health toughness `hpK`, damage share `dmgPct`, attack interval `atk`, `speed`, `rad`, `height`, `aggro`, `per`: camp size - 2)',code('FAM')+' '+loc(MON_DEF_FILE,/^const FAM=/)],
    ['How HP, damage and XP are made from the level (also used by zone tiers and by anything that wants a monster at another level)',code('defAt')+' '+loc(MON_DEF_FILE,/^function defAt/)+', '+code('prepDef')+' '+loc(MON_DEF_FILE,/^function prepDef/)],
    ['The level formulas (expected player damage / health, armour cut, XP, coins)',code('expDmg')+' / '+code('expHP')+' / '+code('xpFor')+' / '+code('coinsFor')+' '+loc(SH+'balance.js',/^const expDmg=/)+'-'+lineOf(SH+'balance.js',/^const coinsFor=/)],
    ['The six bosses, their move set (`kit`), arena, summons (`add`), props, boss-bar texts',code('BOSS_DEFS')+' '+loc(MON_DEF_FILE,/^const BOSS_DEFS=/)],
    ['The grey-veined monsters of the main quest',code('GREY_DEFS')+' '+loc(MON_DEF_FILE,/^const GREY_DEFS=/)],
    ['Every definition in one list (what `DEF_BY_ID` on the server indexes)',code('ALL_MON_DEFS')+' '+loc(MON_DEF_FILE,/^const ALL_MON_DEFS=/)],
    ['How many of each kind exist, and where their camps are (a zone holds 40 of the level-1 kind down to 20 of level 15; the vale and the Reach 12 of each; `count` overrides)',code('MON_COUNT')+' '+loc(SV+'monsters.js',/^const MON_COUNT=/)+', '+code('initMonstersS')+' '+loc(SV+'monsters.js',/^function initMonstersS/)],
    ['Zones (name, level, where): home rings and edges / the Sakura Vale / the Hoarfrost Reach / the Tide King\'s beach',code('ZONES')+' '+loc(SH+'zones.js',/^const ZONES=/)+', '+loc(SH+'vale.js',/^const ARENAS=/)+', '+loc(SH+'hoarfrost.js',/^for\(const A of \[ARENA26/)+', '+loc(SH+'beach.js',/ZONES\.push\(ARENA_TIDE/)],
    ['Monster behaviour (aggro, chase, attack, leash, wander, respawn)',code('updateMonstersS')+' '+loc(SV+'monsters.js',/^function updateMonstersS/)],
    ['What a kill pays (XP, coins, an item roll, the material, quests, boss skills)',code('rewardKill')+' '+loc(SV+'combat.js',/^function rewardKill/)],
    ['Materials a kind drops (one per kind, `MAT_NAMES`)',code('MATS')+' '+loc(SH+'drops.js',/^const MAT_NAMES=/)],
    ['What a zone tier does to a monster (+10 levels per tier)',code('zoneTierK')+' '+loc(SH+'tiers.js',/^function zoneTierK/)+', '+code('monK')+' '+loc(SV+'tiers.js',/^const monK=/)],
    ['Boss fights: engagement, phases, reset / one move set per boss / the move primitives',code('BOSSES')+' '+loc(SV+'boss.js',/^const BOSSES=/)+' / '+code('BOSS_KITS')+' '+loc(SV+'boss-fx.js',/^const BOSS_KITS=/)+' / '+SV+'boss-fx.js'],
    ['The boss notices on the quest board',code('BOSS_QUESTS')+' '+loc(SH+'quests.js',/^const BOSS_QUESTS=/)],
    ['How each model looks (client)','see section 12']])+'\n';

  s+='\n## 2. How the numbers are made\n\n'+
`Let L be the monster's level and \`f(L) = L + (13/12)^L\`.

- **HP** = round(expDmg(L) × (4 + 0.45 L) × hpK × highMult(L)): the hits a same-level, normally geared player needs, times how tough the kind is. \`highMult\` is 1.5 from level ${10} up. A boss or prop has a fixed hit count instead (\`d.hits\`: 70 for a boss, 9 for a prop). \`expDmg(L) = 3 f(L) + TIER_ATK[tierFor(L)]\`.
- **Dmg** (per hit, before the player's armour) = round(expHP(L) × dmgPct / (1 − expRed(L))): a share of a same-level player's health. A boss uses 16%. \`expHP(L) = 20 f(L) + setHP(tierFor(L))\`. Armour then cuts damage by \`def / (def + 60)\`.
- **XP** = xpFor(L) = f(L) × 1.15^(L−5) × highMult (a boss ×25, a prop 0). **Coins** per kill = round(f(L) × U(1.5, 2.5) × 1.1^(L−5) × highMult); the tables show the mean (boss ×20).
- **Hits** in the tables is HP / expDmg(L): how many hits of a same-level, normally geared player it takes.
- **Behaviour**: attack every \`Atk s\` seconds with a 0.28 s wind-up; moves at \`Spd\` m/s; a monster with \`Aggro 0\` ("passive") leaves you alone until hit; it gives up when 32 m from its camp; it only thinks while a player is within 110 m; a dead one respawns after 35 s if nobody is within 22 m of its camp. Bosses engage when a player steps inside their arena and reset when nobody is left inside.
- **Level debuff**: ±5% damage per level of difference between player and monster. **Zone tiers** add 10 levels per tier to every monster of a land, and to a dungeon played at that land's tier (see \`zoneTierK\`); the tables show base values only.
- **Drops**: every kind drops its material with ${W.DROP_CHANCE*100}% (one, sometimes two); a boss always drops ${W.BOSS_DROPS}. An item roll on every kill (monster: 2% common, 0.5% rare, 0.1% epic; boss: 50 / 10 / 3 / 1 / 0.1% common to legendary) of the gear tier of the monster's level (\`tierFor\`, see docs/EQUIPMENT.md). Each boss skill drops from its boss with ${W.BOSS_SKILL_CHANCE*100}% per kill and helper.

`;

  const section=(n,title,note,defs)=>`## ${n}. ${title}\n\n${note}\n\n${monTable(defs)}\n\n`;
  s+='## 3. Reading the tables\n\n**Lv** level; **El** element (`—` = none); **HP** health in the def\'s own units; **Hits** HP / a same-level player\'s damage; **Dmg** damage per hit before armour; **Atk s** seconds between attacks; **Spd** metres per second; **Aggro** distance at which it notices you; **XP** and **Coins** per kill (mean) at base (tier 0); **Count** how many exist; **Drop** its material; **Model** the client model and `scale`; **Defined** file:line of its row.\n\n';
  s+=section(4,'Home forest: the three rings (levels 1-15)','Zones are named by level; ring 0 = levels 1-6, ring 1 = 7-11, ring 2 = 12-15 around the village.',groups.ring);
  s+=section(5,'Home forest: the edges (levels 16-20)','Side content with its own `zone` and `count` (the shore, the Sunwall\'s foot, the Greyspine foothills).',groups.edge);
  s+=section(6,'Sakura Vale (levels 16-25)','Two kinds per level, 12 of each, in ten zones.',groups.vale);
  s+=section(7,'Hoarfrost Reach (levels 22-30)','Two kinds per level, 12 of each, in nine zones.',groups.hoar);

  s+='## 8. Bosses (6)\n\nHealth is 70 hits of a same-level player (×1.5 from level 10); a hit is 16% of that player\'s health. Each boss has its own move set on top of the shared melee and the phases at 60% and 30% (`server/boss.js`).\n\n';
  s+=rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','XP','Coins','Material','Arena','Summons','Prop','Music','Move set','Defined'],W.BOSS_DEFS.map(b=>{
    const d=b.def, L=d.level;
    return [code(d.id),d.name,L,d.el,d.hp,d.dmg,d.atk,d.speed,num(d.xp),coinsAvg(d,L),W.MATS[d.id].name,zoneOf(d,b.arena),b.add?b.add.name:'—',b.prop?b.prop.name:b.totem?b.totem.name:'—',d.music||'boss'+L,
      code(b.kit)+' '+loc(SV+'boss-kits-'+(['roots','tide'].includes(b.kit)?'home':['oni','kitsune'].includes(b.kit)?'vale':'north')+'.js',new RegExp('^BOSS_KITS\\.'+b.kit+'=')),defRef(d)];
  }))+'\n\n';
  s+='Boss quest notices (`BOSS_QUESTS`, '+loc(SH+'quests.js',/^const BOSS_QUESTS=/)+'): '+W.BOSS_QUESTS.map(q=>`${q.title} from level ${q.from}`).join('; ')+'.\n\n';
  s+='### Boss skills (36: a skill and a burst for each class, each with a 10% drop chance per kill)\n\nRows `drop:\'<boss id>\'` at the end of `SKILLS` ('+loc(SH+'classes.js',/^const SKILLS=\{/)+' ...), listed by `BOSS_SKILLS` ('+loc(SH+'drops.js',/^const BOSS_SKILL_CHANCE/)+').\n\n';
  const skRows=[]; for(const b of W.BOSS_DEFS) for(const id of W.BOSS_SKILLS[b.def.id]||[]){ const k=W.SKILLS[id]; skRows.push([b.short,code(id),k.name,W.CLASSES[k.cls].name,k.slot,k.el||'—',k.lv,k.cd+' s',loc(SH+'classes.js',new RegExp('^\\s*'+id+":\\{cls:.*drop:'"))]); }
  s+=rowsOf(['Boss','Id','Skill','Class','Slot','El','Lv','Cooldown','Defined'],skRows)+'\n\n';

  s+='## 9. Boss helpers: summons and props\n\nSummoned by a boss kit or placed by it; not in `MON_DEFS`, so no camps, no quest-board notices and no material. They are in `ALL_MON_DEFS`.\n\n';
  s+=rowsOf(['Id','Name','Lv','El','HP','Dmg','Atk s','Spd','Aggro','XP','Role','Defined'],W.BOSS_DEFS.flatMap(b=>[['add',b.add],['totem',b.totem],['prop',b.prop]].filter(r=>r[1]).map(([kind,d])=>[code(d.id),d.name,d.level,d.el||'—',d.hp,d.noAttack?'—':d.dmg,d.noAttack?'—':d.atk,d.speed||'—',d.aggro?d.aggro+' m':'—',d.noXp?'—':num(d.xp),(kind==='add'?'summoned by ':kind==='totem'?'shield-phase totem of ':'shelter prop of ')+b.short,defRef(d)])))+'\n\n';

  s+='## 10. Grey-veined monsters (main quest)\n\nTougher copies of a zone\'s kind (`greyDef`, tripled XP). Not in `MON_DEFS`: the server spawns a few for each player on that quest step (`server/main-quest.js`).\n\n'+
    rowsOf(MON_HEAD,W.GREY_DEFS.map(monRow))+'\n\n';

  s+='## 11. Level table\n\nThe expected numbers at each level (a same-level player in the gear of their tier, a monster with `hpK` 1): what a dungeon mob at level L would get from `defAt`.\n\n';
  const lv=[]; for(let L=1;L<=W.MAX_ZONE_LV;L++){
    const kills=W.expToNext(L)/W.xpFor(L);
    lv.push([L,num(W.fLv(L)),Math.round(W.expDmg(L)),Math.round(W.expHP(L)),Math.round(W.expRed(L)*100)+'%','T'+(W.tierFor(L)+1),Math.round(W.expDmg(L)*(4+0.45*L)*W.highMult(L)),Math.round(W.expHP(L)*0.10/(1-W.expRed(L))),num(W.xpFor(L)),Math.round(W.expToNext(L)),Math.round(kills),Math.max(1,Math.round(W.fLv(L)*2*Math.pow(1.1,Math.max(0,L-5))*W.highMult(L)))]);
  }
  s+=rowsOf(['L','f(L)','Player dmg','Player HP','Armour cut','Gear tier','Mob HP (hpK 1)','Mob dmg (10%)','XP / kill','XP to next','Kills / level','Coins / kill'],lv)+'\n\n';
  s+='Formulas: '+code('fLv')+' '+loc(SH+'balance.js',/^const fLv=/)+', '+code('tierFor')+' '+loc(SH+'balance.js',/^const tierFor=/)+', '+code('expToNext')+' '+loc(SH+'balance.js',/^const expToNext=/)+' (from level 25 a level costs as many same-level kills as 25 → 26 does).\n\n';

  s+='## 12. Client models\n\nA def\'s `model` picks a family model (`MODELS.<model>={geo,build,anim}`) and its `pal` flags pick the variant (see CLAUDE.md section 4). `FAM` gives each family\'s defaults.\n\n';
  const files=fs.readdirSync(path.join(ROOT,GC)).filter(f=>/^monster-.*\.js$/.test(f)), modelAt={};
  for(const f of files) srcLines(GC+f).forEach((l,i)=>{ const m=/^MODELS\.(\w+)=/.exec(l); if(m) modelAt[m[1]]=GC+f+':'+(i+1); });
  s+=rowsOf(['Model','Kinds using it','Family defaults (hpK / dmgPct / atk s / speed / rad / height / aggro / camp)','Family row','Client model'],Object.keys(W.FAM).map(k=>{
    const F=W.FAM[k], n=W.ALL_MON_DEFS.filter(d=>d.model===k).length;
    return [code(k),n,[F.hpK,F.dmgPct,F.atk,F.speed,F.rad,F.height,F.aggro,F.per+2].join(' / '),loc(MON_DEF_FILE,new RegExp('^  '+k+':\\s*\\{hpK')),modelAt[k]||'—'];
  }))+'\n';
  return s;
}

// =====================================================================  EQUIPMENT.md
const IT=SH+'items.js', BAL=SH+'balance.js';
const ALL_SLOTS_LIST=[...W.WEAPON_SLOTS,...W.ARMOR_SLOTS];
const resName=id=>(W.ORE_GRADES.concat(W.LOG_GRADES).find(g=>g[0]===id)||[id,id])[1];
function levelsOfTier(t){ const ls=[]; for(let L=1;L<=W.MAX_ZONE_LV;L++) if(W.tierFor(L)===t) ls.push(L); return ls.length?(ls.length>1?ls[0]+'-'+ls[ls.length-1]:String(ls[0])):'—'; }
const SLOT_TITLE={sword:'Sword (Warrior weapon)',bow:'Bow (Archer weapon)',wand:'Wand (Mage weapon)',helmet:'Helmet',top:'Top (chest)',bottom:'Bottom (legs)',shoes:'Shoes'};

function equipmentDoc(){
  let s=HEADER('Equipment: every piece of gear and tool','Every item in `ITEM` (7 pieces × 6 level tiers × 5 rarities = 210) and the 90 profession tools, with the numbers the server uses and where they are defined. Dungeon loot (docs/DUNGEONS.md) is built from these.');

  s+='## 1. Where it is defined\n\n'+rowsOf(['What','Where'],[
    ['Every item (generated in two loops from the arrays below): `ITEM`, `ITEM_LIST` (gear: 210), `TOOL_LIST` (tools: 90, in `ITEM` but not in `ITEM_LIST`)',code('ITEM')+' '+loc(IT,/^const ITEM=\{\}/)],
    ['Names of every piece and tier',code('SLOT_NAMES')+' '+loc(IT,/^const SLOT_NAMES=/)],
    ['Level a tier needs',code('TIER_LV')+' '+loc(IT,/^const TIER_LV=/)],
    ['Weapon attack by tier',code('TIER_ATK')+' '+loc(BAL,/^const TIER_ATK=/)],
    ['Armour health and defense by tier and piece',code('ARMOR_HP')+' '+loc(BAL,/^const ARMOR_HP=/)+', '+code('ARMOR_DEF')+' '+loc(BAL,/^const ARMOR_DEF=/)],
    ['Which tier drops at which monster level',code('tierFor')+' '+loc(BAL,/^const tierFor=/)],
    ['Rarities and their multiplier',code('RARITY')+' '+loc(IT,/^const RARITY=/)+', '+code('RAR_MULT')+' '+loc(IT,/^const RAR_MULT=/)],
    ['Base prices (tier) and weight of each piece',code('PRICE')+' '+loc(IT,/^const PRICE=/)+', '+code('SLOT_PRICE')+' '+loc(IT,/^const PRICE=/)],
    ['The item id scheme (`sword2`, `sword2-e`)',code('itemId')+' '+loc(IT,/^const itemId=/)],
    ['Tools (pickaxe, axe, sickle): materials, prices, double-yield chance by rarity',code('TOOL_MAT')+' / '+code('TOOL_PRICE')+' / '+code('TOOL_EXTRA')+' '+loc(IT,/^const TOOL_MAT=/)+'-'+lineOf(IT,/^const TOOL_PRICE=/)],
    ['What gear adds to a player (health, attack, defense)',code('gearStatsOf')+' '+loc(IT,/^function gearStatsOf/)+', '+code('recalcP')+' '+loc(SV+'players.js',/^function recalcP/)],
    ['Wearing an item (level check, slot)',code('equipP')+' '+loc(SV+'economy.js',/^function equipP/)],
    ['Shops: common items only, +20% per copy bought',code('buyP')+' '+loc(SV+'economy.js',/^function buyP/)+', '+code('shopPrice')+' '+loc(IT,/^const SHOP_STEP/)+', shop panel '+loc('src/game/economy/shops.js',/ITEM_LIST\.filter\(i=>ofKind/)],
    ['Monster and boss drops (the item roll and its tier)',code('rollMonsterRarity')+' / '+code('rollBossRarity')+' '+loc(IT,/^function rollMonsterRarity/)+', used in '+code('rewardKill')+' '+loc(SV+'combat.js',/^function rewardKill/)],
    ['Quest board rewards (item rarity)',code('rollQuestItemRarity')+' '+loc(SH+'quests.js',/(function|const) rollQuestItemRarity/)],
    ['Merging three identical items into the next rarity (Greta\'s forge)',code('mergeP')+' '+loc(SV+'economy.js',/^function mergeP/)+', '+code('mergedId')+' '+loc(IT,/^const mergedId/)],
    ['Crafting from ore / logs (rarity common to epic)',code('craftCost')+' '+loc(SH+'crafting.js',/^function craftCost/)+', '+code('craftP')+' '+loc(SV+'crafting.js',/^function craftP/)],
    ['How a piece looks on the character',code('ARMOR_LOOK')+' '+loc(IT,/^const ARMOR_LOOK=/)],
    ['The inventory icon of every piece and tool',loc('src/game/ui/item-icons.js',/^\/\/@/)+' (the file)'],
    ['A save\'s gear (what is worn, what is in the bag)',code('newGearFor')+' '+loc(IT,/^function newGearFor/)+', '+code('sanitizeGear')+' '+loc(SV+'players.js',/^function sanitizeGear/)]])+'\n';

  s+='\n## 2. How the stats are made\n\n'+
`- **Weapon attack** = round(TIER_ATK[tier] × RAR_MULT[rarity]). The weapon you wield sets your class (sword: Warrior, bow: Archer, wand: Mage). A player's damage is \`(3 f(L) + gear attack) × (1 + symbol)\`.
- **Armour health** = round(ARMOR_HP[piece][tier] × RAR_MULT[rarity]); **defense** = max(ARMOR_DEF[piece][tier] + rarity, round(ARMOR_DEF × RAR_MULT)). A player's health is \`(20 f(L) + gear health) × (1 + passives) × (1 + symbol)\`; damage taken is cut by \`def / (def + 60)\`.
- **Price** = round(PRICE[tier] × SLOT_PRICE[piece] × 3^rarity); sells for 40% (\`sellPrice\`). Only **common** items are in the shops, unlimited, each copy bought costs 20% of the base more until sunrise.
- **Level**: an item needs \`lv\` = TIER_LV[tier] (${W.TIER_LV.join(', ')}) to be worn. Tiers 1-4 are the home forest's, 5-6 the Sakura Vale's samurai gear; **tier 6 is the top**: levels 25-30 (the Hoarfrost Reach) still drop tier 6.
- **Rarity** (${W.RARITY.map((r,i)=>r+' ×'+W.RAR_MULT[i]).join(', ')}): ${W.MERGE_COUNT} identical items merge into one of the next rarity at the forge (same tier needed). Drops: a monster 2% common, 0.5% rare, 0.1% epic per kill; a boss 50 / 10 / 3 / 1 / 0.1% (common to legendary). The rarity is rolled first, then one of the seven pieces with equal chance, of the tier of the monster's level (\`tierFor\`).
- **Crafting** makes common, rare and epic pieces only (unique and legendary come from drops and merging); a tier's weapons cost ore, its armour logs, plus 10% of the price in coins.
- Id scheme: \`<piece><tier 1-6>[-r|-e|-u|-l]\`: \`sword2\` is a common Iron Longsword, \`sword2-e\` the epic one.

`;

  s+='## 3. The six tiers\n\n'+rowsOf(['Tier','Level','Dropped at monster levels','Weapon attack (common)','Helmet HP / DEF','Top HP / DEF','Bottom HP / DEF','Shoes HP / DEF','Full set HP','Full set DEF','Base price'],
    W.TIER_LV.map((lvl,t)=>['T'+(t+1),lvl,levelsOfTier(t),W.TIER_ATK[t],...W.ARMOR_SLOTS.map(sl=>W.ARMOR_HP[sl][t]+' / '+W.ARMOR_DEF[sl][t]),W.setHP(t),W.setDef(t),W.PRICE[t]]))+'\n\n';
  s+=rowsOf(['Tier','Sword','Bow','Wand','Helmet','Top','Bottom','Shoes'],W.TIER_LV.map((lvl,t)=>['T'+(t+1),...ALL_SLOTS_LIST.map(sl=>W.SLOT_NAMES[sl][t])]))+'\n\n';
  s+='## 4. Rarities\n\n'+rowsOf(['Rarity','Suffix','Stat multiplier','Price multiplier','Monster drop','Boss drop','Crafted','Tool double-yield chance'],
    W.RARITY.map((r,i)=>[r,i?code('-'+W.RAR_KEY[i]):'(none)','×'+W.RAR_MULT[i],'×'+Math.pow(3,i),['2%','0.5%','0.1%','—','—'][i],['50%','10%','3%','1%','0.1%'][i],i<=W.CRAFT_MAX_RAR?'yes':'no','+'+Math.round(W.TOOL_EXTRA[i]*100)+'%']))+'\n\n';

  s+='## 5. Every piece of gear (210)\n\nOne table per slot, in the order tier, then rarity. **Price** is the item\'s value (the shop price of the first common copy; rarer items are not sold), **Sell** what a shop pays, **Craft** the cost at the smith or armourer (ore for weapons, logs for armour; `—` where it cannot be crafted). **Ref** is the entry of `SLOT_NAMES` the name comes from.\n\n';
  let n=0;
  for(const slot of ALL_SLOTS_LIST){
    const weapon=W.WEAPON_SLOTS.includes(slot), items=W.ITEM_LIST.filter(i=>i.slot===slot);
    s+=`### 5.${++n} ${SLOT_TITLE[slot]}\n\nNames: ${code('SLOT_NAMES.'+slot)} ${loc(IT,new RegExp('^\\s*'+slot+':\\['))}; stats: ${weapon?code('TIER_ATK')+' '+loc(BAL,/^const TIER_ATK=/):code('ARMOR_HP.'+slot)+' / '+code('ARMOR_DEF.'+slot)+' '+loc(BAL,/^const ARMOR_HP=/)+', '+loc(BAL,/^const ARMOR_DEF=/)}${weapon?'':'; look: '+code('ARMOR_LOOK.'+slot)+' '+loc(IT,new RegExp('^\\s*'+(slot==='helmet'?'helmet':slot)+':\\[\\{',''))}.\n\n`;
    s+=rowsOf(['Id','Name','Req Lv','Rarity',...(weapon?['Attack']:['Health','Defense']),'Price','Sell','Craft','Ref'],items.map(it=>{
      let cr='—'; if(it.rar<=W.CRAFT_MAX_RAR){ const c=W.craftCost(slot,it.tier,it.rar); cr=c.n+' × '+resName(c.res)+' + '+c.coins+' c'; }
      return [code(it.id),it.name,it.lv,W.RARITY[it.rar],...(weapon?[it.atk]:[it.hp,it.def]),it.price,W.sellPrice(it),cr,'SLOT_NAMES.'+slot+'['+it.tier+']'];
    }))+'\n\n';
  }

  s+='## 6. Profession tools (90)\n\nThree tool slots (`eq.pick`, `eq.axe`, `eq.sickle`), the same 6 tiers and 5 rarities as gear but **no combat stats**: the tier decides which resource nodes it can work (a node needs a tool of tier `need` or better) and the rarity how often a node gives a double yield. Bought (common only) at a Wayfarers\' Lodge, merged at the forge. Defined in `items.js` ('+loc(IT,/^const TOOL_SLOTS=/)+'), not part of `ITEM_LIST`.\n\n';
  s+=rowsOf(['Ids (common, rare, epic, unique, legendary)','Name (common)','Req Lv','Works nodes of tier','Profession','Price C / R / E / U / L','Ref'],W.TOOL_SLOTS.flatMap(slot=>W.TIER_LV.map((lvl,t)=>{
    const base=slot+(t+1);
    return [W.RAR_KEY.map(k=>code(base+(k?'-'+k:''))).join(', '),W.TOOL_MAT[t]+' '+W.TOOL_KIND[slot],lvl,'T'+(t+1),W.TOOL_PROF[slot],W.RARITY.map((r,i)=>Math.round(W.TOOL_PRICE[t]*Math.pow(3,i))).join(' / '),'TOOL_MAT['+t+'], TOOL_PRICE['+t+']'];
  })))+'\n';
  return s;
}

// ---- write or check ----
const OUT={'docs/MOBS.md':mobsDoc(),'docs/EQUIPMENT.md':equipmentDoc()};
let stale=0;
const noLines=t=>t.replace(/(\.js):\d+(?:-\d+)?/g,'$1:N');
for(const f in OUT){
  const p=path.join(ROOT,f), now=fs.existsSync(p)?fs.readFileSync(p,'utf8'):null;
  if(CHECK){
    if(now===OUT[f]) console.log('ok     '+f);
    else if(now!==null&&noLines(now)===noLines(OUT[f])){ console.log('moved  '+f+' (only line numbers changed: node tools/gen-docs.js refreshes them)'); if(STRICT) stale++; }
    else { stale++; console.log('STALE  '+f+' (run node tools/gen-docs.js)'); }
  } else { fs.writeFileSync(p,OUT[f]); console.log('wrote '+f+' ('+OUT[f].split('\n').length+' lines)'); }
}
process.exit(stale?1:0);
